Content:
    moltres:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
#        content:
#            - js/*
#            - css/*
#            - contrib/**
#            - media/framework/*
#            - templates/stubs/*
#            - syntax/**
#            - source/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    extra-css:
        - css/moltres.css

Extensions:
    MooseDocs.extensions.template:
        active: True
    MooseDocs.extensions.navigation:
        name: Moltres
        repo: https://github.com/arfc/moltres
        menu:
            Getting Started:
               Install Moltres: getting_started/installation.md
               Tutorials: getting_started/tutorials.md
            Documentation:
               Moltres Syntax: syntax/index.md
               Moltres Doxygen: doxygen/classes.html
               MOOSE Syntax: https://mooseframework.inl.gov/source/index.html
               MOOSE Doxygen: https://mooseframework.inl.gov/docs/doxygen/moose/classes.html
            Help: help.md
            Citing: citing.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        unregister: !include ${MOOSE_DIR}/framework/doc/unregister.yml
    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.common:
        shortcuts:
            framework: !include ${MOOSE_DIR}/framework/doc/globals.yml
